apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: quobject-controller
rules:
- apiGroups: [""]
  resources: ["secrets","configmaps"]
  verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch"]
  - apiGroups: ["pascalvandam.io"]
    resources: ["quobjectbucketclaims","quobjectbucketclaims/status","quobjectbucketclaims/finalizers"]
    verbs: ["get","list","watch","update","patch","create","delete"]
