apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: quobjectbucketclaims.pascalvandam.io
spec:
  group: pascalvandam.io
  scope: Namespaced
  names:
    kind: QuObjectBucketClaim
    plural: quobjectbucketclaims
    singular: quobjectbucketclaim
    shortNames:
      - qobc
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            apiVersion:
              type: string
              description: Kubernetes API version
            kind:
              type: string
              description: Kubernetes resource kind
            metadata:
              type: object
            spec:
              type: object
              description: Desired state for creating and wiring an S3 bucket on QNAP QuObjects
              required:
                - qnap_s3_url
                - access_id
                - secret_id
              properties:
                bucketName:
                  type: string
                  description: Exact bucket name to create/use. If omitted, generateBucketName is used.
                generateBucketName:
                  type: string
                  description: Prefix used to generate a unique bucket name (e.g. "demo-bkt-").
                storageClassName:
                  type: string
                  description: Logical class name (optional, for your own routing/quotas).
                access_id:
                  type: string
                  description: S3 access key ID to use for this claim.
                secret_id:
                  type: string
                  format: password
                  description: S3 secret access key to use for this claim.
                qnap_s3_url:
                  type: string
                  description: Base URL for the QuObjects S3 endpoint (e.g., http://s3.kleefdraakjes.nest or https://s3.example:8081)
                region:
                  type: string
                  default: us-east-1
                  description: S3 region to use (keep us-east-1 if your gateway expects empty CreateBucket body).
                additionalConfig:
                  type: object
                  additionalProperties:
                    type: string
                  description: Free-form key/value options for future use (tiering class, replication, etc.).
            status:
              type: object
              properties:
                phase:
                  type: string
                bucketName:
                  type: string
                secretRef:
                  type: string
                configMapRef:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Bucket
          type: string
          jsonPath: .status.bucketName
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

